### ISSUE TITLE
select(everything()) doesn't drop other columns as designed

### ISSUE THREAD

**Issue by leungi** [asardaes/table.express#7]
Reprex below.

With `dplyr::everything()`, any columns pre-selected will not be included in `everything()`, but this is not the case when evaluated with `start_expr()`.

Ideas: in `.select_matching()`, need an extra `if-else` to handle `everything()` by doing a `setdiff()` on pre-selected columns (i.e., anything captured by '...' argument that is not a `tidyselect::select_helpers` verb)

``` r

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(table.express)
#> 
#> Attaching package: 'table.express'
#> The following object is masked from 'package:dplyr':
#> 
#>     order_by
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(data.table)
#> Warning: package 'data.table' was built under R version 3.5.3
#> 
#> Attaching package: 'data.table'
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last

DT = data.table(x = letters[1:5], y = 1:5, z = 1:5 > 3)

# intended
DT %>% 
  mutate(id = row_number()) %>% 
  select(id, everything())
#>   id x y     z
#> 1  1 a 1 FALSE
#> 2  2 b 2 FALSE
#> 3  3 c 3 FALSE
#> 4  4 d 4  TRUE
#> 5  5 e 5  TRUE

# extra id column
DT %>% 
  start_expr() %>% 
  mutate(id = .I) %>% 
  select(id, everything()) %>% 
  end_expr()
#>    id x y     z id
#> 1:  1 a 1 FALSE  1
#> 2:  2 b 2 FALSE  2
#> 3:  3 c 3 FALSE  3
#> 4:  4 d 4  TRUE  4
#> 5:  5 e 5  TRUE  5
```

<sup>Created on 2019-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by asardaes** [comment]
I can add this special case, however, do bear in mind that simply selecting columns (as done with, for example, `select` with tidy helpers) results in a deep copy of the selected columns. These copies are necessary because one could then modify the resulting data table by reference, and if no copy were made, the previous table would also be modified. This is why `data.table` has functions like `setcolorder`,
so something like this would be better in any case:

```r
DT %>% 
  start_expr() %>% 
  mutate(id = .I) %>% 
  end_expr() %>%
  setcolorder("id")
```

This is only to say that I think having `tidyselect` helpers is definitely nice for convenience in many scenarios, but if you're working with truly big tables that require the optimizations offered by `data.table`,
you'll probably want to avoid certain operations.

**Comment by leungi** [comment]
Thanks for clarification @asardaes.

If I understand your comment fully, `select()` evaluated within `start_expr()` context will be modified-in-place, so long as there's no `tidyselect::select_helpers` in it; otherwise, it'll be copied by reference, by default, even if `.by_ref = TRUE` when ending evaluation with `end_expr()`.

If the above is correct, then I agree with you that it's best to stick with the `data.table` principle that everything should be modified-in-place; as such, let's keep behaviour as is.

I'm surprised `data.table` allows duplicated column names 😨 

On a side note, your package has helped me learn `data.table` at a faster pace than before; thank you!

I can't seem to find you on twitter, otherwise, I'll tag you along with #table.express; it's very underrated 😄

**Comment by asardaes** [comment]
`select` will *always* result in a copy, regardless of how it's used. This would still be true even if you were using `data.table` by itself:

```r
DT2 <- DT[, x:z][, y := y - 1L]
```

Everything between `x` and `z` needs to be copied so that modifying `y` afterwards only affects what will be assigned to `DT2`, leaving `DT` intact.

That's why I wrote in the vignette that `select` is one verb you might not want to use with `data.table`, at least not in the way it's usually used in `dplyr`.

**Comment by leungi** [comment]
You did make the note about `select()` in the vignette; I grasp what it means now.

Pardon my ignorance as I uncover `data.table`.

**Comment by asardaes** [comment]
It's not a problem, I also don't know all the intricacies of either `data.table` or `dplyr`, and deep copies during selection isn't too intuitive. Maybe I'll extend the vignette disclaimer with more specific wording.
